// =============================================================
// SNN_Accelerator.sv  —  ASIC synthesis version
// Change from original (rtl/top/SNN_Accelerator.sv):
//   $readmemh("weights_conv.hex") replaced with localparam ROM
//   Run asic/scripts/gen_weights.py to fill in CONV_WEIGHTS.
// =============================================================
module SNN_Accelerator #(
    parameter int IMG_WIDTH   = 28,
    parameter int NUM_FILTERS = 8,
    parameter int DATA_WIDTH  = 8,
    parameter int ACC_WIDTH   = 18,
    parameter int V_THRESH    = 59723
) (
    input  logic       clk,
    input  logic       rst_n,
    input  logic       frame_rst_n,
    input  logic       s_axis_valid,
    output logic       s_axis_ready,
    input  logic [7:0] s_axis_data,
    output logic       m_axis_valid,
    output logic [NUM_FILTERS-1:0] m_axis_spike,
    output logic       m_frame_done
);

    // ---------------------------------------------------------
    // Conv weights as localparam ROM (synthesis-safe)
    // 8 filters x 9 taps = 72 signed 8-bit values
    // Generated by: python3 asic/scripts/gen_weights.py
    // ---------------------------------------------------------
    localparam logic signed [7:0] CONV_WEIGHTS [0:71] = '{
        8'sh59, 8'sh6B, 8'shDC, 8'sh62, 8'sh0A, 8'shFD, 8'shCC, 8'sh2C, 8'sh3C  // filter 0,
        8'sh81, 8'sh4F, 8'sh33, 8'sh1C, 8'sh25, 8'sh4A, 8'shED, 8'sh50, 8'sh17  // filter 1,
        8'shEC, 8'sh0D, 8'shB9, 8'sh04, 8'shD4, 8'sh17, 8'shB5, 8'shC9, 8'shCF  // filter 2,
        8'shBD, 8'shE6, 8'sh8B, 8'sh72, 8'shEA, 8'sh2F, 8'sh44, 8'sh24, 8'sh5D  // filter 3,
        8'shEE, 8'sh51, 8'sh13, 8'shD9, 8'sh2E, 8'shF0, 8'sh3D, 8'sh69, 8'sh3E  // filter 4,
        8'sh1C, 8'sh72, 8'sh58, 8'sh77, 8'shED, 8'sh96, 8'shBD, 8'sh8C, 8'sh10  // filter 5,
        8'shFE, 8'sh03, 8'shF5, 8'shE8, 8'sh21, 8'shA7, 8'shE2, 8'shA5, 8'shF1  // filter 6,
        8'shE8, 8'sh0F, 8'shED, 8'sh25, 8'shBA, 8'shE0, 8'shB0, 8'sh2D, 8'sh1E  // filter 7
    };

    // ---------------------------------------------------------
    // Internal signals (unchanged from original)
    // ---------------------------------------------------------
    logic                  lb_valid;
    logic [8:0][7:0]       lb_window;
    logic                  o_skip;
    logic                  o_fire_enable;
    logic                  fsm_clear_mem;
    logic [9:0]            vmem_addr;
    logic [9:0]            waddr_q;

    logic signed [ACC_WIDTH-1:0] vmem_read_data  [0:NUM_FILTERS-1];
    logic signed [ACC_WIDTH-1:0] vmem_write_data [0:NUM_FILTERS-1];
    logic                        pe_vmem_valid   [0:NUM_FILTERS-1];

    // Weight array wired from localparam (replaces $readmemh)
    logic signed [8:0][7:0] weights_mem [0:NUM_FILTERS-1];
    genvar gw, kw;
    generate
        for (gw = 0; gw < NUM_FILTERS; gw = gw + 1) begin : GEN_W_FILTER
            for (kw = 0; kw < 9; kw = kw + 1) begin : GEN_W_TAP
                assign weights_mem[gw][kw] = CONV_WEIGHTS[gw*9 + kw];
            end
        end
    endgenerate

    assign s_axis_ready = 1'b1;

    // ---------------------------------------------------------
    // Submodule instantiations (unchanged from original)
    // ---------------------------------------------------------
    LineBuffer #(.IMG_WIDTH(IMG_WIDTH), .DATA_WIDTH(DATA_WIDTH)) u_linebuffer (
        .clk    (clk),
        .rst_n  (frame_rst_n),
        .i_valid(s_axis_valid & s_axis_ready),
        .i_data (s_axis_data),
        .o_valid(lb_valid),
        .o_window(lb_window)
    );

    SparsityController u_sparsity (
        .i_window     (lb_window),
        .i_valid      (lb_valid),
        .o_skip       (o_skip),
        .o_fire_enable(o_fire_enable)
    );

    TimeStep_FSM u_fsm (
        .clk        (clk),
        .rst_n      (rst_n),
        .i_lb_valid (lb_valid),
        .o_clear_mem(fsm_clear_mem),
        .o_vmem_addr(vmem_addr),
        .o_frame_done(m_frame_done)
    );

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) waddr_q <= '0;
        else if (lb_valid) waddr_q <= vmem_addr;
    end

    genvar gi;
    generate
        for (gi = 0; gi < NUM_FILTERS; gi = gi + 1) begin : GEN_PE_CHANNEL
            Vmem_Array #(.ACC_WIDTH(ACC_WIDTH)) u_vmem (
                .clk    (clk),
                .i_we   (pe_vmem_valid[gi]),
                .i_raddr(vmem_addr),
                .i_waddr(waddr_q),
                .i_wdata(vmem_write_data[gi]),
                .o_rdata(vmem_read_data[gi])
            );

            ConvPE #(
                .DATA_WIDTH(DATA_WIDTH),
                .ACC_WIDTH (ACC_WIDTH),
                .V_THRESH  (V_THRESH)
            ) u_pe (
                .clk         (clk),
                .rst_n       (rst_n),
                .i_valid     (lb_valid),
                .i_clear_mem (fsm_clear_mem),
                .i_vmem_read (vmem_read_data[gi]),
                .i_window    (lb_window),
                .i_weights   (weights_mem[gi]),
                .i_skip      (o_skip),
                .o_spike     (m_axis_spike[gi]),
                .o_vmem_valid(pe_vmem_valid[gi]),
                .o_vmem_write(vmem_write_data[gi])
            );
        end
    endgenerate

    always_ff @(posedge clk or negedge rst_n) begin
        if (!rst_n) m_axis_valid <= 1'b0;
        else        m_axis_valid <= lb_valid;
    end

endmodule
