#!/usr/bin/env python3
"""
gen_weights.py
Converts weights_conv.hex into SystemVerilog localparam format.

Usage:
    python3 asic/scripts/gen_weights.py

Output: paste the printed block into asic/src/SNN_Accelerator.sv
        replacing the placeholder lines under CONV_WEIGHTS.

Expects weights_conv.hex to be in the same directory as this script,
OR edit HEX_PATH below to point to the correct location.
"""

import os

HEX_PATH = os.path.join(os.path.dirname(__file__), "../../data/weights_conv.hex")
NUM_FILTERS = 8
TAPS = 9
TOTAL = NUM_FILTERS * TAPS  # 72

def main():
    try:
        with open(HEX_PATH) as f:
            raw = f.read().split()
    except FileNotFoundError:
        print(f"ERROR: Cannot find {HEX_PATH}")
        print("Edit HEX_PATH in this script to point to your weights_conv.hex")
        return

    if len(raw) < TOTAL:
        print(f"ERROR: Expected {TOTAL} values, got {len(raw)}")
        return

    vals = [int(x, 16) & 0xFF for x in raw[:TOTAL]]

    print("    // AUTO-GENERATED by asic/scripts/gen_weights.py")
    print(f"    localparam logic signed [7:0] CONV_WEIGHTS [0:{TOTAL-1}] = '{{")
    lines = []
    for f in range(NUM_FILTERS):
        chunk = vals[f*TAPS:(f+1)*TAPS]
        sv_vals = ", ".join(f"8'sh{v:02X}" for v in chunk)
        lines.append(f"        {sv_vals}  // filter {f}")
    print(",\n".join(lines))
    print("    };")

if __name__ == "__main__":
    main()
